### ISSUE TITLE
Option to buy regular keys and not just FO?

### ISSUE THREAD

**Issue by lcreed** [dabidobido/mmmbot#1]
I'm looking at the code but can't figure out how to modify it to buy gobbiedial keys in bulk rather than just the FOs.  It appears to be the  buy_key_fo_option_index but i'm not sure what it needs to be changed to in order to buy something different on the menu.  Any suggestions?

**Comment by dabidobido** [comment]
You will need to use packetviewer and see what the option index is when you buy a gobbie key instead of a dial key FO
